name: Deploy API to Koyeb

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Koyeb CLI
        run: |
          curl -sSL https://get.koyeb.app | sh
          echo "$HOME/.koyeb/bin" >> $GITHUB_PATH

      - name: Authenticate Koyeb CLI
        run: koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}

      - name: Deploy latest version
        run: koyeb service redeploy project-biot-team-001
