name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_IOT_TEAM_001 }}
          channelId: live
          projectId: iot-team-001
